version: '3'
services:
  my-stack-db:
    image: ghcr.io/jarmee/my-stack-db:${MY_STACK_VERSION}
    container_name: my-stack-db-${MY_STACK_DEPLOYMENT}
    restart: on-failure:5
    networks:
      - traefik-proxy
    environment:
      POSTGRES_DB: 'mystack'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
    volumes:
      - ./db-data:/data/db
    labels:
      - 'traefik.enable=false'

  my-stack-client:
    image: ghcr.io/jarmee/my-stack-client:${MY_STACK_VERSION}
    container_name: my-stack-client-${MY_STACK_DEPLOYMENT}
    restart: on-failure:5
    networks:
      - traefik-proxy
    labels:
      - 'traefik.http.routers.my-stack-client-${MY_STACK_DEPLOYMENT}.rule=Host(`${MY_STACK_PREFIX}mystack.letz.dev`)'

  my-stack-api:
    image: ghcr.io/jarmee/my-stack-api:${MY_STACK_VERSION}
    container_name: my-stack-api-${MY_STACK_DEPLOYMENT}
    restart: on-failure:5
    networks:
      - traefik-proxy
    environment:
      DB_HOST: 'my-stack-db'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
    labels:
      - 'traefik.http.routers.my-stack-api-${MY_STACK_DEPLOYMENT}.rule=Host(`${MY_STACK_PREFIX}mystack.letz.dev`) && PathPrefix(`/api`)'

networks:
  traefik-proxy:
    external: true
