version: "3"
services:
  my-stack-db:
    image: ghcr.io/jarmee/my-stack-db:develop
    environment:
      POSTGRES_DB: mystack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - my-stack-data:/data/db

  my-stack-client:
    image: ghcr.io/jarmee/my-stack-client:develop
    ports:
      - 8081:80

  my-stack-api:
    image: ghcr.io/jarmee/my-stack-api:develop
    environment:
      # FIXME
    ports:
      - 3333:3333

volumes:
  my-stack-data:
