version: '3'
services:
  my-stack-db:
    image: ghcr.io/jarmee/my-stack-db:${MY_STACK_VERSION:-local}
    environment:
      POSTGRES_DB: mystack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - my-stack-data:/data/db

  my-stack-client:
    image: ghcr.io/jarmee/my-stack-client:${MY_STACK_VERSION:-local}
    ports:
      - 8081:80

  my-stack-api:
    image: ghcr.io/jarmee/my-stack-api:${MY_STACK_VERSION:-local}
    environment:
      DB_HOST: my-stack-db
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: secret
    ports:
      - 3333:3333

volumes:
  my-stack-data:
