version: "3.1"
services:
  my-stack-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mystack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - my-stack-data:/data/db
volumes:
  my-stack-data:
