name: quality

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/28-create-deployment-pipelines" # FIXME
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Run NX Quality Targets
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint,test,build