name: quality

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run NX Targets
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint,test,build